version: '3.9'

services:
  backend:
    container_name: AMS_BACKEND
    build: 
      context: ./backend
    
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
  
  frontend:
    container_name: AMS_FRONTEND

    build: 
      context: ./frontend
    
    command: npm run dev

    volumes:
      - ./frontend:/src
    
    ports:
      - 3000:3000
    depends_on:
      - backend
