import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Setup } from "@/Components/utils";
import { Provider } from "@/redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Account Transfer Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className + " bg-gray-100"}>
        <Provider>
          <Setup />
          {children}
        </Provider>
        </body>
    </html>
  );
}
